---

- hosts: all
  become: true
  tasks:
  - name: Update packages, install Apache package and PHP support for it - Ubuntu & CentOS
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
