---

- hosts: all
  become: true
  tasks:
  - name: Update index
    apt:
      update_cache: true

  - name: Install Apache2 package
    apt:
      name: apache2
      state: latest

  - name: Add PHP support for Apache
    apt:
      name: libapache2-mod-php
      state: latest
