---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: workstations
  become: true
  tasks:
  - name: Install unzip
    tags: workstation,popos
    package:
      name: unzip

  - name: Install terraform
    tags: workstation,popos
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_386.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_server
  become: true
  tasks:
  - name: Install Apache and PHP for Web servers(Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache and PHP for Web servers(CentOS)
    dnf:
      name:
      tags: apache,httpd,centos
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy html file to web server
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true
  tasks:
  - name: Install MariaDB(Ubuntu)
    tags: mariadb,ubuntu,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install MariaDB(CentOS)
    dnf:
      name: mariadb
      tags: db,mariadb,centos
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_server
  become: true
  tasks:
  - name: Install Samba(Ubuntu & CentOS)
    tags: ubuntu,centos,samba
    package:
      name: samba
      state: latest
