---

- hosts: all
  become: true
  tasks:
  - name: Update index
    apt:
      update_cache: true

  - name: Uinstall Apache2 package
    apt:
      name: apache2
      state: absent

  - name: Remove PHP support for Apache
    apt:
      name: libapache2-mod-php
      state: absent
